// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using solutionthree.Models.Database;

namespace solutionthree.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20210511214253_First")]
    partial class First
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("solutionthree.Models.Person", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("firstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("lastName")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("person");

                    b.HasData(
                        new
                        {
                            id = 1,
                            age = 27,
                            firstName = "Joe",
                            lastName = "Soap"
                        },
                        new
                        {
                            id = 2,
                            age = 35,
                            firstName = "Daniel",
                            lastName = "Moshe"
                        },
                        new
                        {
                            id = 3,
                            age = 29,
                            firstName = "Seth",
                            lastName = "Smith"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
